### ISSUE TITLE
Transactions root mismatch

### ISSUE THREAD

**Issue by tongson** [attestantio/vouch#140]
From time to time we see:
```
"error":"transactions root mismatch"
```

What could be causing this? 

We do mix Teku and Lighthouse in `beacon-node-addresseses`, would that be a problem?

**Comment by mcdee** [comment]
This happens when a beacon node is asked for a blinded beacon block but it does not fetch the execution payload from Vouch.  Some beacon nodes have the idea of a circuit breaker, where it will build a local payload if certain conditions are met.  Each beacon node has its own configuration and parameters, so you'd have to look at that to see what is configured and either adjust the parameters or turn the circuit breaker off entirely.

**Comment by tongson** [comment]
Thank you very much for pointing this out.

Gonna check configs.
