### ISSUE TITLE
Issue with connection to prysm node

### ISSUE THREAD

**Issue by stefa2k** [attestantio/vouch#34]
```
{"level":"error","error":"failed to select submitter: failed to fetch client <ip:port> for submitter strategy: failed to initiate client: failed to confirm node connection: failed to fetch genesis: failed to request genesis: failed to call GET endpoint: Get \"http://<ip:port>/eth/v1/beacon/genesis\": net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"","time":"2021-10-21T15:09:43Z","message":"Failed to initialise services"}
```

Replaced the actual ip and port with `<ip:port>`

Versions:
vouch: `1.2.2`
prysm: `v2.0.1`

**Comment by mcdee** [comment]
Looks like you are attempting to connect to the gRPC connection.  Vouch now uses prysm's REST API.  Please take a read through https://github.com/attestantio/vouch/releases/tag/v1.2.1 and ensure that you have both processes configured correctly (also note that the earliest supported version of prysm is 2.0.2, due to bugs in its REST API in 2.0.1).

**Comment by pursonchen** [comment]
Great solution, I was involved in this issue for weeks.
