### ISSUE TITLE
"POTENTIAL DEADLOCK" on beacon chain head update

### ISSUE THREAD

**Issue by stefa2k** [attestantio/vouch#5]
[vouch-deadlock.txt](https://github.com/attestantio/vouch/files/5542727/vouch-deadlock.txt)

**Comment by mcdee** [comment]
There are two pieces here.  The first is the exit on potential deadlock, which is working as intended.  This relates back to our "fail fast" methodology, where if something isn't doing what it should then we bail and allow the restart to take care of things.

The second is _why_ the update is taking so long.  Due to the nature of Vouch, with various network connections, we can have to wait a long time for responses.  That said, 30 seconds is too long given that we're running on a 12-second tick.  We will take a look through the code and ensure that any slot-related activities have a suitable timeout attached to them to ensure that the overall operation either completes within the given time slot, or fails.

**Comment by mcdee** [comment]
The code path for head updates has been optimised in release 1.3.2 so this should no longer occur.
